### ISSUE TITLE
Neptune.js Export statement

### ISSUE THREAD

**Issue by NotSujal** [NotSujal/Neptune.js#4]
When you import neptune.js file, you import all the classes of Neptune, this is degrading performance.
Need a way to fix the performance issue, and import only the classes needed by the user.

**Comment by Ansh-code398** [comment]
Just dont use 
```js
import * as npt from "@neptunejs/neptune";
```
Use
```js
import {Circle, Application} from "@neptunejs/neptune"; // Etc.
```

**Comment by NotSujal** [comment]
The suggested method is not working.
This is the Import Statement
![image](https://user-images.githubusercontent.com/85174767/171427942-a83a4780-d440-4aa5-9981-20de3a8f2b9a.png)

All the files are loading in this case.
![image2](https://user-images.githubusercontent.com/85174767/171427937-1660282f-51e7-4833-bf17-882f80c9e551.png)

**Comment by Ansh-code398** [comment]
Ok I will fix it

**Comment by Ansh-code398** [comment]
Well there is only one solution
# Dont import like this way

```js
import Application from "https://cdn.jsdelivr.net/npm/@neptune-js/neptune@latest/src/main.js" // Or @neptune-js/neptune/src/main.js if using npm
```
use this way

and you will get this 

![image](https://user-images.githubusercontent.com/73456520/172327420-a9bb462e-64fb-4f61-b90e-748d8eb874ef.png)
