### ISSUE TITLE
Try it Yourself

### ISSUE THREAD

**Issue by NotSujal** [NotSujal/Neptune.js#6]
Add a try it yourself editor in the documentation.
Which can quickly run the code on the output panel/frame.

**Comment by Ansh-code398** [comment]
You cant Ig cuz you are using jsdoc

**Comment by NotSujal** [comment]
@Ansh-code398  
The editor is added in the [Tutorials /Live Editor](https://neptune-js.vercel.app/tutorial-Live%20Editor.html).
Using CodeMirror for this purpose.

Not finalized. Do test the Editor.

**Comment by Ansh-code398** [comment]
@NotSujal ok
