### ISSUE TITLE
Better events.

### ISSUE THREAD

**Issue by Ansh-code398** [NotSujal/Neptune.js#7]
@NotSujal 
Use Pointer Events instead of touch and mouse events. It will save you a lot of time and others devs can make game for both devices easily.

**Comment by NotSujal** [comment]
Yes, going to rewrite events.

There are the planed changes.
* Easy to use with Input Actions ( upcomming).
* Input visualizer. Addition to gizmos.
* Tutorials of events in documentation.
* Mouse and touch events will share the same name, Pointer
